apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: e99j4y5hb-go 
  janus-idp.io/tekton: e99j4y5hb-go
  backstage.io/kubernetes-id: e99j4y5hb-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: e99j4y5hb-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml